// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package commons

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// for obtaining Status Code from response messages from server
// to parse response into suitable object
type GenericResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{0}
}
func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (dst *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(dst, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type GenericRequest struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericRequest) Reset()         { *m = GenericRequest{} }
func (m *GenericRequest) String() string { return proto.CompactTextString(m) }
func (*GenericRequest) ProtoMessage()    {}
func (*GenericRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{1}
}
func (m *GenericRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericRequest.Unmarshal(m, b)
}
func (m *GenericRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericRequest.Marshal(b, m, deterministic)
}
func (dst *GenericRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericRequest.Merge(dst, src)
}
func (m *GenericRequest) XXX_Size() int {
	return xxx_messageInfo_GenericRequest.Size(m)
}
func (m *GenericRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericRequest proto.InternalMessageInfo

func (m *GenericRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// S_JOIN_RESPONSE = 100
type RegisterResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Err                  string   `protobuf:"bytes,5,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{2}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegisterResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DiceMixResponse struct {
	Code                 uint32       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Peers                []*PeersInfo `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
	Timestamp            string       `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string       `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Err                  string       `protobuf:"bytes,5,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DiceMixResponse) Reset()         { *m = DiceMixResponse{} }
func (m *DiceMixResponse) String() string { return proto.CompactTextString(m) }
func (*DiceMixResponse) ProtoMessage()    {}
func (*DiceMixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{3}
}
func (m *DiceMixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiceMixResponse.Unmarshal(m, b)
}
func (m *DiceMixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiceMixResponse.Marshal(b, m, deterministic)
}
func (dst *DiceMixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiceMixResponse.Merge(dst, src)
}
func (m *DiceMixResponse) XXX_Size() int {
	return xxx_messageInfo_DiceMixResponse.Size(m)
}
func (m *DiceMixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiceMixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiceMixResponse proto.InternalMessageInfo

func (m *DiceMixResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DiceMixResponse) GetPeers() []*PeersInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *DiceMixResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DiceMixResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DiceMixResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type PeersInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	NumMsgs              uint32   `protobuf:"varint,3,opt,name=NumMsgs,proto3" json:"NumMsgs,omitempty"`
	DCVector             []uint64 `protobuf:"varint,4,rep,packed,name=DCVector,proto3" json:"DCVector,omitempty"`
	DCSimpleVector       [][]byte `protobuf:"bytes,5,rep,name=DCSimpleVector,proto3" json:"DCSimpleVector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersInfo) Reset()         { *m = PeersInfo{} }
func (m *PeersInfo) String() string { return proto.CompactTextString(m) }
func (*PeersInfo) ProtoMessage()    {}
func (*PeersInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{4}
}
func (m *PeersInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersInfo.Unmarshal(m, b)
}
func (m *PeersInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersInfo.Marshal(b, m, deterministic)
}
func (dst *PeersInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersInfo.Merge(dst, src)
}
func (m *PeersInfo) XXX_Size() int {
	return xxx_messageInfo_PeersInfo.Size(m)
}
func (m *PeersInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeersInfo proto.InternalMessageInfo

func (m *PeersInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PeersInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeersInfo) GetNumMsgs() uint32 {
	if m != nil {
		return m.NumMsgs
	}
	return 0
}

func (m *PeersInfo) GetDCVector() []uint64 {
	if m != nil {
		return m.DCVector
	}
	return nil
}

func (m *PeersInfo) GetDCSimpleVector() [][]byte {
	if m != nil {
		return m.DCSimpleVector
	}
	return nil
}

// C_KEY_EXCHANGE = 2
type KeyExchangeRequest struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	NumMsgs              uint32   `protobuf:"varint,4,opt,name=NumMsgs,proto3" json:"NumMsgs,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyExchangeRequest) Reset()         { *m = KeyExchangeRequest{} }
func (m *KeyExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeRequest) ProtoMessage()    {}
func (*KeyExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{5}
}
func (m *KeyExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeRequest.Unmarshal(m, b)
}
func (m *KeyExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeRequest.Marshal(b, m, deterministic)
}
func (dst *KeyExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeRequest.Merge(dst, src)
}
func (m *KeyExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeRequest.Size(m)
}
func (m *KeyExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeRequest proto.InternalMessageInfo

func (m *KeyExchangeRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *KeyExchangeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KeyExchangeRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *KeyExchangeRequest) GetNumMsgs() uint32 {
	if m != nil {
		return m.NumMsgs
	}
	return 0
}

func (m *KeyExchangeRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

// C_EXP_DC_VECTOR = 3
type DCExpRequest struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	DCExpVector          []uint64 `protobuf:"varint,3,rep,packed,name=DCExpVector,proto3" json:"DCExpVector,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCExpRequest) Reset()         { *m = DCExpRequest{} }
func (m *DCExpRequest) String() string { return proto.CompactTextString(m) }
func (*DCExpRequest) ProtoMessage()    {}
func (*DCExpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{6}
}
func (m *DCExpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCExpRequest.Unmarshal(m, b)
}
func (m *DCExpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCExpRequest.Marshal(b, m, deterministic)
}
func (dst *DCExpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCExpRequest.Merge(dst, src)
}
func (m *DCExpRequest) XXX_Size() int {
	return xxx_messageInfo_DCExpRequest.Size(m)
}
func (m *DCExpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCExpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCExpRequest proto.InternalMessageInfo

func (m *DCExpRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DCExpRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DCExpRequest) GetDCExpVector() []uint64 {
	if m != nil {
		return m.DCExpVector
	}
	return nil
}

func (m *DCExpRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

// S_EXP_DC_VECTOR = 103
type DCExpResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Roots                []uint64 `protobuf:"varint,2,rep,packed,name=Roots,proto3" json:"Roots,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Err                  string   `protobuf:"bytes,5,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCExpResponse) Reset()         { *m = DCExpResponse{} }
func (m *DCExpResponse) String() string { return proto.CompactTextString(m) }
func (*DCExpResponse) ProtoMessage()    {}
func (*DCExpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{7}
}
func (m *DCExpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCExpResponse.Unmarshal(m, b)
}
func (m *DCExpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCExpResponse.Marshal(b, m, deterministic)
}
func (dst *DCExpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCExpResponse.Merge(dst, src)
}
func (m *DCExpResponse) XXX_Size() int {
	return xxx_messageInfo_DCExpResponse.Size(m)
}
func (m *DCExpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DCExpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DCExpResponse proto.InternalMessageInfo

func (m *DCExpResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DCExpResponse) GetRoots() []uint64 {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *DCExpResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DCExpResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DCExpResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// C_SIMPLE_DC_VECTOR = 4
type DCSimpleRequest struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	DCSimpleVector       [][]byte `protobuf:"bytes,3,rep,name=DCSimpleVector,proto3" json:"DCSimpleVector,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCSimpleRequest) Reset()         { *m = DCSimpleRequest{} }
func (m *DCSimpleRequest) String() string { return proto.CompactTextString(m) }
func (*DCSimpleRequest) ProtoMessage()    {}
func (*DCSimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b1d5eadd7a689b1, []int{8}
}
func (m *DCSimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCSimpleRequest.Unmarshal(m, b)
}
func (m *DCSimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCSimpleRequest.Marshal(b, m, deterministic)
}
func (dst *DCSimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCSimpleRequest.Merge(dst, src)
}
func (m *DCSimpleRequest) XXX_Size() int {
	return xxx_messageInfo_DCSimpleRequest.Size(m)
}
func (m *DCSimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCSimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCSimpleRequest proto.InternalMessageInfo

func (m *DCSimpleRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DCSimpleRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DCSimpleRequest) GetDCSimpleVector() [][]byte {
	if m != nil {
		return m.DCSimpleVector
	}
	return nil
}

func (m *DCSimpleRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericResponse)(nil), "commons.GenericResponse")
	proto.RegisterType((*GenericRequest)(nil), "commons.GenericRequest")
	proto.RegisterType((*RegisterResponse)(nil), "commons.RegisterResponse")
	proto.RegisterType((*DiceMixResponse)(nil), "commons.DiceMixResponse")
	proto.RegisterType((*PeersInfo)(nil), "commons.PeersInfo")
	proto.RegisterType((*KeyExchangeRequest)(nil), "commons.KeyExchangeRequest")
	proto.RegisterType((*DCExpRequest)(nil), "commons.DCExpRequest")
	proto.RegisterType((*DCExpResponse)(nil), "commons.DCExpResponse")
	proto.RegisterType((*DCSimpleRequest)(nil), "commons.DCSimpleRequest")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_5b1d5eadd7a689b1) }

var fileDescriptor_messages_5b1d5eadd7a689b1 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0xab, 0xda, 0x40,
	0x10, 0xc6, 0xd9, 0x6c, 0x52, 0xeb, 0xa8, 0xd1, 0x2e, 0x3d, 0x2c, 0xa5, 0x87, 0x10, 0xda, 0x92,
	0x93, 0x87, 0xf6, 0x4f, 0x48, 0xa4, 0x88, 0x58, 0x64, 0x5b, 0x7a, 0xd7, 0x38, 0x4d, 0x03, 0x26,
	0x9b, 0xee, 0x46, 0x50, 0x7a, 0x29, 0xf4, 0xde, 0x6b, 0x79, 0xff, 0xed, 0xc3, 0x4d, 0xa2, 0x4f,
	0x9f, 0x04, 0x04, 0x6f, 0x3b, 0x9f, 0xe3, 0xce, 0x6f, 0xbf, 0x6f, 0x08, 0xb8, 0x19, 0x6a, 0xbd,
	0x4c, 0x50, 0x8f, 0x0b, 0x25, 0x4b, 0xc9, 0x3a, 0xb1, 0xcc, 0x32, 0x99, 0x6b, 0xff, 0x3d, 0x0c,
	0x3f, 0x63, 0x8e, 0x2a, 0x8d, 0x05, 0xea, 0x42, 0xe6, 0x1a, 0x19, 0x03, 0x3b, 0x94, 0x6b, 0xe4,
	0xc4, 0x23, 0xc1, 0x40, 0x98, 0xb3, 0xff, 0x0e, 0xdc, 0x63, 0xdb, 0xaf, 0x2d, 0xea, 0xf2, 0x6a,
	0xd7, 0x1f, 0x02, 0x23, 0x81, 0x49, 0xaa, 0x4b, 0x54, 0x6d, 0xd7, 0x31, 0x17, 0xac, 0xe9, 0x9a,
	0x5b, 0x1e, 0x09, 0x5e, 0x09, 0x6b, 0xba, 0x66, 0x6f, 0xa1, 0xfb, 0x2d, 0xcd, 0x50, 0x97, 0xcb,
	0xac, 0xe0, 0xd4, 0x23, 0x41, 0x57, 0x9c, 0x04, 0xc6, 0xa1, 0x33, 0xaf, 0xf0, 0xb9, 0x6d, 0x7e,
	0x6b, 0x4a, 0x36, 0x02, 0x3a, 0x51, 0x8a, 0x3b, 0x46, 0x3d, 0x1c, 0xfd, 0x07, 0x02, 0xc3, 0x28,
	0x8d, 0x71, 0x9e, 0xee, 0x5a, 0x09, 0x02, 0x70, 0x16, 0x88, 0x4a, 0x73, 0xcb, 0xa3, 0x41, 0xef,
	0x23, 0x1b, 0xd7, 0x86, 0x8c, 0x8d, 0x3a, 0xcd, 0x7f, 0x48, 0x51, 0x35, 0xdc, 0x91, 0xed, 0x3f,
	0x81, 0xee, 0xf1, 0xfa, 0xda, 0x83, 0x03, 0x93, 0xd3, 0x78, 0xb0, 0xd8, 0xae, 0x36, 0x69, 0x3c,
	0xc3, 0xbd, 0xb1, 0xa6, 0x2f, 0x4e, 0xc2, 0x61, 0xce, 0x97, 0x6d, 0x36, 0xd7, 0x89, 0x36, 0x0c,
	0x03, 0xd1, 0x94, 0xec, 0x0d, 0xbc, 0x8c, 0xc2, 0xef, 0x18, 0x97, 0x52, 0x71, 0xdb, 0xa3, 0x81,
	0x2d, 0x8e, 0x35, 0xfb, 0x00, 0x6e, 0x14, 0x7e, 0x4d, 0xb3, 0x62, 0x83, 0x75, 0x87, 0xe3, 0xd1,
	0xa0, 0x2f, 0x2e, 0x54, 0xff, 0x1f, 0x01, 0x36, 0xc3, 0xfd, 0x64, 0x17, 0xff, 0x5c, 0xe6, 0x09,
	0xb6, 0x64, 0x7c, 0x2d, 0xba, 0x13, 0x36, 0x6d, 0xc1, 0xb6, 0xcf, 0xb1, 0xcf, 0x6c, 0x75, 0x2e,
	0x6c, 0xf5, 0x15, 0xf4, 0xa3, 0x70, 0xb2, 0x2b, 0x6e, 0x21, 0xf1, 0xa0, 0x67, 0xfe, 0x53, 0xbf,
	0x94, 0x1a, 0x2f, 0x9e, 0x4a, 0xe7, 0x33, 0xed, 0xcb, 0x99, 0x7f, 0x09, 0x0c, 0xea, 0xa1, 0x2d,
	0x8b, 0xf3, 0x1a, 0x1c, 0x21, 0x65, 0x59, 0x2d, 0x8e, 0x2d, 0xaa, 0xe2, 0x8e, 0x4b, 0xf2, 0x1b,
	0x86, 0x4d, 0x38, 0xb7, 0x3c, 0xfe, 0x79, 0xd2, 0xf4, 0x5a, 0xd2, 0xed, 0x16, 0xac, 0x5e, 0x98,
	0xaf, 0xc3, 0xa7, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x16, 0x11, 0x32, 0x2f, 0x04, 0x00,
	0x00,
}
