// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package commons

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// for obtaining Status Code from response messages from server
// to parse response into suitable object
type GenericResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{0}
}
func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (dst *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(dst, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// Response returned by server when attempt to join dicemix
// S_JOIN_RESPONSE
type RegisterResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Err                  string   `protobuf:"bytes,5,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{1}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegisterResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// Response returned by server for -
// StartDiceMix - Code S_START_DICEMIX
// KeyExchangeResponse - Code S_KEY_EXCHANGE
// DCSimpleResponse - Code S_SIMPLE_DC_VECTOR
type DiceMixResponse struct {
	Code                 uint32       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Peers                []*PeersInfo `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
	Timestamp            string       `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string       `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Err                  string       `protobuf:"bytes,5,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DiceMixResponse) Reset()         { *m = DiceMixResponse{} }
func (m *DiceMixResponse) String() string { return proto.CompactTextString(m) }
func (*DiceMixResponse) ProtoMessage()    {}
func (*DiceMixResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{2}
}
func (m *DiceMixResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiceMixResponse.Unmarshal(m, b)
}
func (m *DiceMixResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiceMixResponse.Marshal(b, m, deterministic)
}
func (dst *DiceMixResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiceMixResponse.Merge(dst, src)
}
func (m *DiceMixResponse) XXX_Size() int {
	return xxx_messageInfo_DiceMixResponse.Size(m)
}
func (m *DiceMixResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiceMixResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiceMixResponse proto.InternalMessageInfo

func (m *DiceMixResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DiceMixResponse) GetPeers() []*PeersInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *DiceMixResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DiceMixResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DiceMixResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// Sub-message for DiceMixResponse
type PeersInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	NumMsgs              uint32   `protobuf:"varint,3,opt,name=NumMsgs,proto3" json:"NumMsgs,omitempty"`
	DCVector             []uint64 `protobuf:"varint,4,rep,packed,name=DCVector,proto3" json:"DCVector,omitempty"`
	DCSimpleVector       [][]byte `protobuf:"bytes,5,rep,name=DCSimpleVector,proto3" json:"DCSimpleVector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersInfo) Reset()         { *m = PeersInfo{} }
func (m *PeersInfo) String() string { return proto.CompactTextString(m) }
func (*PeersInfo) ProtoMessage()    {}
func (*PeersInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{3}
}
func (m *PeersInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersInfo.Unmarshal(m, b)
}
func (m *PeersInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersInfo.Marshal(b, m, deterministic)
}
func (dst *PeersInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersInfo.Merge(dst, src)
}
func (m *PeersInfo) XXX_Size() int {
	return xxx_messageInfo_PeersInfo.Size(m)
}
func (m *PeersInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeersInfo proto.InternalMessageInfo

func (m *PeersInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PeersInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PeersInfo) GetNumMsgs() uint32 {
	if m != nil {
		return m.NumMsgs
	}
	return 0
}

func (m *PeersInfo) GetDCVector() []uint64 {
	if m != nil {
		return m.DCVector
	}
	return nil
}

func (m *PeersInfo) GetDCSimpleVector() [][]byte {
	if m != nil {
		return m.DCSimpleVector
	}
	return nil
}

// For broadcasting our public key
// to initiate KeyExchange
// Code - C_KEY_EXCHANGE
type KeyExchangeRequest struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	NumMsgs              uint32   `protobuf:"varint,4,opt,name=NumMsgs,proto3" json:"NumMsgs,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyExchangeRequest) Reset()         { *m = KeyExchangeRequest{} }
func (m *KeyExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeRequest) ProtoMessage()    {}
func (*KeyExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{4}
}
func (m *KeyExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeRequest.Unmarshal(m, b)
}
func (m *KeyExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeRequest.Marshal(b, m, deterministic)
}
func (dst *KeyExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeRequest.Merge(dst, src)
}
func (m *KeyExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeRequest.Size(m)
}
func (m *KeyExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeRequest proto.InternalMessageInfo

func (m *KeyExchangeRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *KeyExchangeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KeyExchangeRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *KeyExchangeRequest) GetNumMsgs() uint32 {
	if m != nil {
		return m.NumMsgs
	}
	return 0
}

func (m *KeyExchangeRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

// For broadcasting our DC Exponential Vector
// to initiate DC-EXP
// Code - C_EXP_DC_VECTOR
type DCExpRequest struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	DCExpVector          []uint64 `protobuf:"varint,3,rep,packed,name=DCExpVector,proto3" json:"DCExpVector,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCExpRequest) Reset()         { *m = DCExpRequest{} }
func (m *DCExpRequest) String() string { return proto.CompactTextString(m) }
func (*DCExpRequest) ProtoMessage()    {}
func (*DCExpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{5}
}
func (m *DCExpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCExpRequest.Unmarshal(m, b)
}
func (m *DCExpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCExpRequest.Marshal(b, m, deterministic)
}
func (dst *DCExpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCExpRequest.Merge(dst, src)
}
func (m *DCExpRequest) XXX_Size() int {
	return xxx_messageInfo_DCExpRequest.Size(m)
}
func (m *DCExpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCExpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCExpRequest proto.InternalMessageInfo

func (m *DCExpRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DCExpRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DCExpRequest) GetDCExpVector() []uint64 {
	if m != nil {
		return m.DCExpVector
	}
	return nil
}

func (m *DCExpRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

// Response against DCExpRequest
// conatins ROOTS calculated by server using FLINT
// Code - S_EXP_DC_VECTOR
type DCExpResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Roots                []uint64 `protobuf:"varint,2,rep,packed,name=Roots,proto3" json:"Roots,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Err                  string   `protobuf:"bytes,5,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCExpResponse) Reset()         { *m = DCExpResponse{} }
func (m *DCExpResponse) String() string { return proto.CompactTextString(m) }
func (*DCExpResponse) ProtoMessage()    {}
func (*DCExpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{6}
}
func (m *DCExpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCExpResponse.Unmarshal(m, b)
}
func (m *DCExpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCExpResponse.Marshal(b, m, deterministic)
}
func (dst *DCExpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCExpResponse.Merge(dst, src)
}
func (m *DCExpResponse) XXX_Size() int {
	return xxx_messageInfo_DCExpResponse.Size(m)
}
func (m *DCExpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DCExpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DCExpResponse proto.InternalMessageInfo

func (m *DCExpResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DCExpResponse) GetRoots() []uint64 {
	if m != nil {
		return m.Roots
	}
	return nil
}

func (m *DCExpResponse) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DCExpResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DCExpResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// For broadcasting our DC Simple Vector
// to initiate DC-SIMPLE
// C_SIMPLE_DC_VECTOR
type DCSimpleRequest struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Id                   int32    `protobuf:"zigzag32,2,opt,name=Id,proto3" json:"Id,omitempty"`
	DCSimpleVector       [][]byte `protobuf:"bytes,3,rep,name=DCSimpleVector,proto3" json:"DCSimpleVector,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DCSimpleRequest) Reset()         { *m = DCSimpleRequest{} }
func (m *DCSimpleRequest) String() string { return proto.CompactTextString(m) }
func (*DCSimpleRequest) ProtoMessage()    {}
func (*DCSimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_736ade064468b63a, []int{7}
}
func (m *DCSimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DCSimpleRequest.Unmarshal(m, b)
}
func (m *DCSimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DCSimpleRequest.Marshal(b, m, deterministic)
}
func (dst *DCSimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCSimpleRequest.Merge(dst, src)
}
func (m *DCSimpleRequest) XXX_Size() int {
	return xxx_messageInfo_DCSimpleRequest.Size(m)
}
func (m *DCSimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DCSimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DCSimpleRequest proto.InternalMessageInfo

func (m *DCSimpleRequest) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DCSimpleRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DCSimpleRequest) GetDCSimpleVector() [][]byte {
	if m != nil {
		return m.DCSimpleVector
	}
	return nil
}

func (m *DCSimpleRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericResponse)(nil), "commons.GenericResponse")
	proto.RegisterType((*RegisterResponse)(nil), "commons.RegisterResponse")
	proto.RegisterType((*DiceMixResponse)(nil), "commons.DiceMixResponse")
	proto.RegisterType((*PeersInfo)(nil), "commons.PeersInfo")
	proto.RegisterType((*KeyExchangeRequest)(nil), "commons.KeyExchangeRequest")
	proto.RegisterType((*DCExpRequest)(nil), "commons.DCExpRequest")
	proto.RegisterType((*DCExpResponse)(nil), "commons.DCExpResponse")
	proto.RegisterType((*DCSimpleRequest)(nil), "commons.DCSimpleRequest")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_736ade064468b63a) }

var fileDescriptor_messages_736ade064468b63a = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0x59, 0xad, 0x54, 0xd7, 0xe3, 0xbf, 0x5d, 0x7a, 0x58, 0x4a, 0x0f, 0x42, 0xd0, 0xa2,
	0x93, 0x0f, 0xed, 0x23, 0x48, 0xa6, 0x18, 0xe3, 0x62, 0xb6, 0xa5, 0x77, 0x5b, 0x9e, 0xaa, 0x02,
	0x4b, 0xab, 0xee, 0xca, 0x60, 0x93, 0x4b, 0x20, 0xf7, 0x5c, 0x43, 0xde, 0x36, 0x78, 0x25, 0xd9,
	0xb1, 0x13, 0x44, 0x0c, 0xbe, 0xcd, 0x7c, 0x1a, 0x69, 0x7e, 0xf3, 0xcd, 0x08, 0xfa, 0x29, 0x6a,
	0xbd, 0x88, 0x51, 0x8f, 0x72, 0x25, 0x0b, 0xc9, 0x5a, 0x91, 0x4c, 0x53, 0x99, 0x69, 0xef, 0x0b,
	0x0c, 0x7e, 0x60, 0x86, 0x2a, 0x89, 0x04, 0xea, 0x5c, 0x66, 0x1a, 0x19, 0x03, 0x3b, 0x90, 0x2b,
	0xe4, 0xc4, 0x25, 0x7e, 0x4f, 0x98, 0xd8, 0xbb, 0x25, 0x30, 0x14, 0x18, 0x27, 0xba, 0x40, 0xd5,
	0x54, 0xc8, 0xfa, 0x60, 0x4d, 0x56, 0xdc, 0x72, 0x89, 0xff, 0x41, 0x58, 0x93, 0x15, 0xfb, 0x0c,
	0xed, 0xdf, 0x49, 0x8a, 0xba, 0x58, 0xa4, 0x39, 0xa7, 0x2e, 0xf1, 0xdb, 0xe2, 0x28, 0x30, 0x0e,
	0xad, 0x59, 0x09, 0xc6, 0x6d, 0xf3, 0xac, 0x4e, 0xd9, 0x10, 0xe8, 0x58, 0x29, 0xee, 0x18, 0x75,
	0x1f, 0x7a, 0x8f, 0x04, 0x06, 0x61, 0x12, 0xe1, 0x2c, 0xd9, 0x36, 0x12, 0xf8, 0xe0, 0xcc, 0x11,
	0x95, 0xe6, 0x96, 0x4b, 0xfd, 0xce, 0x37, 0x36, 0xaa, 0x46, 0x1d, 0x19, 0x75, 0x92, 0xfd, 0x95,
	0xa2, 0x2c, 0xb8, 0x22, 0xdb, 0x03, 0x81, 0xf6, 0xe1, 0xf3, 0x95, 0x07, 0x7b, 0x26, 0xa7, 0xf6,
	0x60, 0xbe, 0x59, 0xae, 0x93, 0x68, 0x8a, 0x3b, 0x63, 0x4d, 0x57, 0x1c, 0x85, 0x7d, 0x9f, 0x9f,
	0x9b, 0x74, 0xa6, 0x63, 0x6d, 0x18, 0x7a, 0xa2, 0x4e, 0xd9, 0x27, 0x78, 0x1f, 0x06, 0x7f, 0x30,
	0x2a, 0xa4, 0xe2, 0xb6, 0x4b, 0x7d, 0x5b, 0x1c, 0x72, 0xf6, 0x15, 0xfa, 0x61, 0xf0, 0x2b, 0x49,
	0xf3, 0x35, 0x56, 0x15, 0x8e, 0x4b, 0xfd, 0xae, 0x38, 0x53, 0xbd, 0x7b, 0x02, 0x6c, 0x8a, 0xbb,
	0xf1, 0x36, 0xfa, 0xb7, 0xc8, 0x62, 0x14, 0xf8, 0x7f, 0x83, 0xba, 0x78, 0xeb, 0xea, 0x8e, 0xd8,
	0xb4, 0x01, 0xdb, 0x3e, 0xc5, 0x3e, 0xb1, 0xd5, 0x39, 0xb3, 0xd5, 0x53, 0xd0, 0x0d, 0x83, 0xf1,
	0x36, 0xbf, 0x84, 0xc4, 0x85, 0x8e, 0x79, 0xa7, 0x9a, 0x94, 0x1a, 0x2f, 0x9e, 0x4b, 0xa7, 0x3d,
	0xed, 0xf3, 0x9e, 0x77, 0x04, 0x7a, 0x55, 0xd3, 0x86, 0xc3, 0xf9, 0x08, 0x8e, 0x90, 0xb2, 0x28,
	0x0f, 0xc7, 0x16, 0x65, 0x72, 0xc5, 0x23, 0xb9, 0x81, 0x41, 0xbd, 0x9c, 0x4b, 0x86, 0x7f, 0xb9,
	0x69, 0xfa, 0xda, 0xa6, 0x9b, 0x2d, 0x58, 0xbe, 0x33, 0xff, 0xfd, 0xf7, 0xa7, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xaf, 0x42, 0x21, 0x63, 0x09, 0x04, 0x00, 0x00,
}
